#!/bin/bash

set -e

display_init() {
	systemctl stop display

	cat /sys/class/leds/display/max_brightness > /sys/class/leds/display/brightness
}

display_cleanup() {
	systemctl start display
}

display_text() {
	TEXT="$1"
	PADDING="$2"
	SLEEP="$3"

	if [ -n "$PADDING" ]; then
		for i in $(seq 1 $DIGITS); do
			TEXT="$PADDING$TEXT$PADDING"
		done
	fi

	while [ "${#TEXT}" -ge "$DIGITS" ]; do
		echo "${TEXT:0:$DIGITS}" > /sys/class/leds/display/value
		TEXT="${TEXT:1}"
		sleep $SLEEP
	done
}

display_check() {
	echo "all digits and leds on"
	echo 88888888 > /sys/class/leds/display/value
	for led in /sys/class/leds/display::*; do
		echo 1 > $led/brightness
	done
	sleep 1

	echo "all digitd and leds off"
	echo > /sys/class/leds/display/value
	for led in /sys/class/leds/display::*; do
		echo 0 > $led/brightness
	done

	echo "digit order: 1234"
	echo 12345678 > /sys/class/leds/display/value
	sleep 1

	for led in /sys/class/leds/display::*; do
		echo 1 > $led/brightness
		led_name="${led##*:}"
		led_name="${led_name@U}"
		echo "led ${led_name} on"
		display_text "${led_name}" " " 0.25
		echo 0 > $led/brightness
	done
}


trap display_cleanup SIGHUP SIGTERM SIGQUIT SIGKILL SIGINT

DIGITS=$(cat /sys/class/leds/display/num_digits)

usage() {
	echo "Usage:"
	echo "  $0 -t <text_to_display>"
	echo "  $0 -c"
	exit 1
}

if [ "$1" == "-t" ]; then
	[ $# -ne 2 ] && usage
	display_init
	display_text "$2" " " 0.5
	display_cleanup

elif [ "$1" == "-c" ]; then
	display_init
	display_check
	display_cleanup

else
	usage
fi
